name: test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: test
        if: github.event_name.push == 'push'
        run: |
          echo Hello, world!
          echo ${{ github.event_name }}
