name: test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: test
        if: github.event_name.push == 'push'
        run: |
          echo Hello, world!
      - name: echo
        run: |
          echo ${{ github.event_name }}
          echo ${{ github.event_name.push }}
