name: test

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: test
        if: startsWith(github.ref, 'refs/tags')
        run: |
          echo Hello, world!
      - name: echo
        run: |
          echo ${{ github }}
          echo ${{ github.event_name }}
          echo ${{ github.ref}}
          echo ${{ github.event.ref }}
